trainer:
  num_epochs: 300
  warmup: 2
  lr: 0.0001
  optimizer: adamw
  weight_decay: 0.05
  betas: [0.9, 0.95]

dataset:
  root: ./datasets
  img_size: 352
  batch_size: 4
  num_workers: 0

models:
  FCBFormer_D:
    checkpoint_root: ./src/models/model_components/pvt_v2_b3.pth




